### ISSUE TITLE
Project roadmap

### ISSUE THREAD

**Issue by silveryiris** [silveryiris/frontend-crypto-coin-demo#1]
- [x] mock api server
- [x] popup modal
- [x] mobile layout only
- [x] load env
- [x] cryptocompare.com api
